### ISSUE TITLE
window disappearing

### ISSUE THREAD

**Issue by DylanSijanivandi** [avme/avme-wallet#27]
window disappears when attempting to drag edge of window to enlarge it.

**Comment by itamarcps** [comment]
Please provide further information about your system, specially which Operating System you are using and which version of it.
A video recording of the issue will be highly appreciated.

**Comment by DylanSijanivandi** [comment]
https://youtu.be/wf3LsFWstBs

Windows 10
AVME BETA 1.1

**Comment by itamarcps** [comment]
> 
> 
> https://youtu.be/wf3LsFWstBs
> 
> Windows 10
> AVME BETA 1.1

Thank you! We will be looking towards this issue when refactoring the GUI.

**Comment by itamarcps** [comment]
Hello! @DylanSijanivandi 
Could you please try the newest version located in our releases and see if the issue still happens? Thank you anyway.

**Comment by backfliptildeps** [comment]
Hi

I have a problem at Ubuntu 20.04. How does this issue solve? 

$ ./avme-gui 
Fontconfig error: Cannot load default config file

**Comment by Jean-Lessa** [comment]
@backfliptildeps I had this issue as well on my KDE rig, decided to have a look at it yesterday and I think I found a fix, should be merged by next release. Check #50.

As for this issue in specific, I'm closing it for now due to inactivity. We're long past 1.1 so I'm not sure the bug still exists since OP hasn't replied for months.
